---
- name: Tailscale の公式 GPG キーを追加
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/noble.gpg
    state: present

- name: Tailscale の公式リポジトリを追加
  apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/ubuntu noble main"
    state: present

- name: Tailscale をインストール
  apt:
    name: tailscale
    state: present
    update_cache: true

- name: Tailscale を起動・自動起動設定
  systemd:
    name: tailscaled
    state: started
    enabled: true

- name: Tailscale でネットワークに参加
  command: tailscale up --authkey={{ tailscale_auth_key }} --accept-routes
  args:
    creates: /var/lib/tailscale/tailscaled.state
