---
- name: Tailscale をインストール（公式スクリプト）
  ansible.builtin.shell: curl -fsSL https://tailscale.com/install.sh | sh
  args:
    creates: /usr/bin/tailscale

- name: Tailscale を起動・自動起動設定
  systemd:
    name: tailscaled
    state: started
    enabled: true

- name: Tailscale でネットワークに参加
  command: tailscale up --authkey={{ tailscale_auth_key }} --accept-routes
  args:
    creates: /var/lib/tailscale/tailscaled.state
